title: R&P Blog
author: R&P
email: R&P@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
       R&P Blog POST.
  
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
